apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-fluentd-service
  labels:
{{ include "sindan-server.labels" . | indent 4 }}
spec:
  selector:
    app: fluentd
{{ include "sindan-server.labels" . | indent 4 }}
  ports:
    - name: fluentd
      protocol: TCP
      port: 8888
      targetPort: {{ .Values.fluentd.servicePort }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql
  labels:
{{ include "sindan-server.labels" . | indent 4 }}
spec:
  selector:
    app: mysql
{{ include "sindan-server.labels" . | indent 4 }}
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-visualization
  labels:
{{ include "sindan-server.labels" . | indent 4 }}
spec:
  selector:
    app: visualization
{{ include "sindan-server.labels" . | indent 4 }}
  ports:
    - name: visualization
      protocol: TCP
      port: 3000
      targetPort: {{ .Values.visualization.servicePort }}
